version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: contacts-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: contacts-api
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL} 
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

volumes:
  pgdata:
